# Generated by Django 5.1 on 2026-03-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('pasword', models.CharField(max_length=20)),
            ],
        ),
    ]
