# Generated by Django 4.2.29 on 2026-03-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0006_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='share_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
