# Generated by Django 4.2.16 on 2026-03-27 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_username', models.CharField(max_length=100)),
                ('total_repos', models.IntegerField(default=0)),
                ('total_stars', models.IntegerField(default=0)),
                ('languages', models.JSONField(default=dict)),
                ('account_age_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score', models.IntegerField(default=0)),
                ('skills', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_one', models.CharField(max_length=100)),
                ('developer_two', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_one', to='analyzer.analysisreport')),
                ('report_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_two', to='analyzer.analysisreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
