# Generated by Django 4.2.16 on 2026-03-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
