# Generated by Django 4.2.16 on 2026-03-28 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzer', '0002_analysisreport_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('profile_text', models.TextField()),
                ('professional_score', models.IntegerField(default=0)),
                ('summary_strength', models.IntegerField(default=0)),
                ('experience_impact', models.IntegerField(default=0)),
                ('keyword_density', models.IntegerField(default=0)),
                ('impact_keywords', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('missing_elements', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
