# Generated by Django 4.2.16 on 2026-03-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_linkedinreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinreport',
            name='experience_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='linkedinreport',
            name='jd_match_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linkedinreport',
            name='suggested_headlines',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='linkedinreport',
            name='target_jd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
