# Generated by Django 4.2.7
"""
Practical 11: Django Database Connectivity (SQLite or MySQL)
This migration creates the initial database tables for:
  - Doctor         (Practical 7, 11, 12, 15)
  - PatientProfile (Practical 13)
  - Appointment    (Practical 14, 16)

Run with:
    python manage.py migrate
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Practical 7, 11, 12, 15: Create Doctor table
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(
                    choices=[
                        ('cardiologist', 'Cardiologist'),
                        ('dermatologist', 'Dermatologist'),
                        ('neurologist', 'Neurologist'),
                        ('orthopedic', 'Orthopedic'),
                        ('pediatrician', 'Pediatrician'),
                        ('psychiatrist', 'Psychiatrist'),
                        ('general', 'General Physician'),
                        ('dentist', 'Dentist'),
                        ('ophthalmologist', 'Ophthalmologist'),
                        ('gynecologist', 'Gynecologist'),
                    ],
                    default='general',
                    max_length=100,
                )),
                ('qualification', models.CharField(max_length=300)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Gujarat', max_length=100)),
                # Practical 15: availability field shown in customized admin
                ('availability', models.CharField(
                    choices=[
                        ('available', 'Available'),
                        ('busy', 'Busy'),
                        ('on_leave', 'On Leave'),
                    ],
                    default='available',
                    max_length=20,
                )),
                # Practical 20: Latitude and Longitude for Google Maps
                ('latitude', models.DecimalField(blank=True, decimal_places=6,
                                                  max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6,
                                                   max_digits=9, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True,
                                                     upload_to='doctor_profiles/')),
                ('consultation_fee', models.DecimalField(decimal_places=2,
                                                          default=500.0, max_digits=8)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['name'],
            },
        ),

        # Practical 13: Create PatientProfile table
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True,
                                                     upload_to='patient_profiles/')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='patient_profile',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
        ),

        # Practical 14 & 16: Create Appointment table
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('confirmed', 'Confirmed'),
                        ('cancelled', 'Cancelled'),
                        ('completed', 'Completed'),
                    ],
                    default='pending',
                    max_length=20,
                )),
                ('payment_status', models.CharField(
                    choices=[
                        ('unpaid', 'Unpaid'),
                        ('paid', 'Paid'),
                        ('refunded', 'Refunded'),
                    ],
                    default='unpaid',
                    max_length=20,
                )),
                # Practical 16: Paytm transaction ID stored here
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2,
                                                     default=0.0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='appointments',
                    to='doctor.doctor',
                )),
                ('patient', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='appointments',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
