mystr = "this"
print(mystr)
print(mystr[0])
print(mystr[-1])
print(mystr[0:4]) #Slice(Range)
print(mystr[5:])
print(mystr[:4])

print(len(mystr))

# String Methods
print(mystr)
print(mystr.strip())
print(mystr.upper())
print(mystr.lower())
print(mystr.replace('i','I'))
print(mystr.replace('This','That'))
print(mystr.split())
print(mystr.capitalize())
print(mystr.casefold())
print(mystr.count("This"))
print(mystr.count("i"))
print(mystr.startswith("T"))
print(mystr.endswith("!"))
print(mystr.find("P"))
print(mystr.index("t"))

print(mystr.isalpha())
print(mystr.isalnum())
print(mystr.isdigit())
print(mystr.islower())
print(mystr.isupper())
print(mystr.title())