mystr = "this"
print(mystr)
print(mystr[0])
print(mystr[-1])
print(mystr[0:4]) #Slice(Range)
print(mystr[5:])
print(mystr[:4])

print(len(mystr))

# String Methods
print(mystr)
print('Strip Method:',mystr.strip())
print('Upper Method:',mystr.upper())
print('Lower Method:',mystr.lower())
print('Replace Method:',mystr.replace('i','I'))
print('Replace Method:',mystr.replace('This','That'))
print('Split Method:',mystr.split())
print('Capitalize Method:',mystr.capitalize())
print('Casefold Method:',mystr.casefold())
print('Count Method:',mystr.count("This"))
print('Count Method:',mystr.count("i"))
print('Startswith Method:',mystr.startswith("T"))
print('Endswith Method:',mystr.endswith("!"))
print('Find Method:',mystr.find("P"))
print('Index Method:',mystr.index("t"))

print('Isalpha Method:',mystr.isalpha())
print('Isalnum Method:',mystr.isalnum())
print('Isdigit Method:',mystr.isdigit())
print('Islower Method:',mystr.islower())
print('Isupper Method:',mystr.isupper())
print('Title Method:',mystr.title())