from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('register/', views.register_view, name='register'),
    path('verify-otp/', views.verify_otp_view, name='verify_otp'),
    path('create-note/', views.create_note_view, name='create_note'),
    path('edit-note/<int:note_id>/', views.edit_note_view, name='edit_note'),
    path('delete-note/<int:note_id>/', views.delete_note_view, name='delete_note'),
    path('toggle-pin/<int:note_id>/', views.toggle_pin_view, name='toggle_pin'),
    path('categories/', views.manage_categories_view, name='manage_categories'),
    path('categories/delete/<int:category_id>/', views.delete_category_view, name='delete_category'),
    path('profile/', views.profile_view, name='profile'),
    path('change-password/', views.change_password_view, name='change_password'),
    path('archive/note/<int:note_id>/', views.archive_note_view, name='archive_note'),
    path('unarchive/note/<int:note_id>/', views.unarchive_note_view, name='unarchive_note'),
    path('archive/', views.archive_list_view, name='archive_list'),
    path('trash/', views.trash_view, name='trash'),
    path('trash/restore/<int:note_id>/', views.restore_note_view, name='restore_note'),
    path('trash/delete/<int:note_id>/', views.permanent_delete_note_view, name='permanent_delete'),
    path('activity-log/', views.activity_log_view, name='activity_log'),
    path('share/<int:note_id>/', views.share_note_view, name='share_note'),
    path('generate-link/<int:note_id>/', views.generate_public_link_view, name='generate_public_link'),
    path('public/<uuid:token>/', views.public_note_view, name='public_note'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('reset-password/', views.reset_password_view, name='reset_password'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]
