# Generated by Django 5.1 on 2026-03-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersignup',
            old_name='pasword',
            new_name='password',
        ),
    ]
